name: Tip Request
description: Request a GitHub Tip from MishManners
title: "to get new key"
labels: "new key"
assignees:
  - sadanandpg
body:
  
  - type: input
    id: Name
    attributes:
      label: More information1
      
      
    validations:
      required: true

  - type: textarea
    id: info
    attributes:
      label: More information
      description: Add more information on the tip you would like to see.
      render: shell
    validations:
      required: true

 
